// <auto-generated />
namespace MusicHub.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrackErrors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackErrors));
        
        string IMigrationMetadata.Id
        {
            get { return "201301151946264_TrackErrors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
