// <auto-generated />
namespace MusicHub.EntityFramework.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSongPlayCounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSongPlayCounts));
        
        string IMigrationMetadata.Id
        {
            get { return "201301081739445_AddSongPlayCounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
